WIP - Better support decryption of Large Files
openpgpjs/openpgpjs pull request #1462
Opened 2022-01-07 08:04 UTC by justin-lovell

Note: This PR is a WIP.

# Introduction

We are working on larger files which result in the process crashing with the following stack trace, and reproduced with the following commit: https://github.com/justin-lovell/openpgpjs/commit/68c7c29bd140202591550c20d895af426d769e07
```
node:buffer:602
    slice: (buf, start, end) => buf.ucs2Slice(start, end),
                                    ^

Error: Failed to allocate memory
    at Object.slice (node:buffer:602:37)
    at Uint8Array.toString (node:buffer:811:14)
    at TextDecoder.decode (node:internal/encoding:431:18)
    at r (C:\src\card-data-importer-poc\node_modules\openpgp\dist\node\openpgp.min.js:2:14559)
    at C:\src\card-data-importer-poc\node_modules\openpgp\dist\node\openpgp.min.js:2:6762
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_MEMORY_ALLOCATION_FAILED'
```

Based on research, it appears the function `unarmor` for the decoding is the culprit -- essentially, the function's implementation reads the entire file to determine whether the checksum computes.

This has been a long standing issue as per the following issues:
* https://github.com/openpgpjs/openpgpjs/issues/1012
* https://github.com/openpgpjs/openpgpjs/issues/1449

# Tasks

- [ ] Eliminate all calls to `stream.readToEnd` within `unarmor`
- [ ] Delay reading checksum (off by default -- still performed at end of stream)
- [ ] Checksum pass only (for users who require an upfront verification)
- [ ] Update documentation to refer to best practices for handling large files (two-phase pass).

2022-01-07 08:06 UTC, justin-lovell commented
Also, the changes are not going to allow options to bypass security features. For large files, having the checksum at the end of the file and NodeJS streams not being seekable is rather annoying.

2022-01-19 00:38 UTC, justin-lovell commented
After annotating and fully understanding the library, the key preventing streaming of large payloads comes down to the option of `allowUnauthenticatedStream`.

https://github.com/openpgpjs/openpgpjs/blob/6da1c53de7852000fd63bacf1809b7e1ea17cf11/src/packet/sym_encrypted_integrity_protected_data.js#L137-L139

As such, this PR will be changed to document/prove that large blobs can be handled by `openpgp.js` and make the appropriate annotations on the documentation.

2022-01-31 12:05 UTC, larabr requested changes
Thanks for proposing the changes and adding the test. We were looking into the best way to benchmark using large data, and using a generator does seem to work well!
I left some comments, since the code needs some changes to reduce variability of benchmark results across runs.
I would also add a second version of the same test, but setting `allowUnauthenticatedStream = false` (like the version you committed before). For that reason, I left a comment on the "outdated" code too.

About documentation, I'd rather not include "how-to" information in the source code, as it will still miss a lot of context. Instead, we are planning to add a Wiki page about streaming with all the relevant info. This is also because, for instance, `config.allowUnauthenticatedStream` will become less relevant once the new OpenPGP spec is released (#1442), thanks to better support for streaming at the protocol level.

2022-06-02 14:15 UTC, larabr approved these changes
Thanks for the contribution @justin-lovell . I've taken over since it's been some time.

In addition to adding tests over large files, I uniformed data generation across all streaming tests to be able to compare the results. I also added output stream consumption, otherwise the decryption operation isn't actually triggered in all cases (this was already an issue with the existing AEAD streaming tests as well).

2022-06-02 14:35 UTC, twiss approved these changes

2022-06-02 15:29 UTC, merged