Fix SignaturePacket.verify() Typescript definition
openpgpjs/openpgpjs pull request #1494
Opened 2022-02-10 22:05 UTC by IvanPizhenko

According to doc comment in signature.js:
```javascript
  /**
   * verifies the signature packet. Note: not all signature types are implemented
   * ...
   * @param {String|Object} data - Data which on the signature applies
   * ...
   */
```
But it was `Uint8Array` currently in the openpgp.d.ts.

2022-02-10 22:14 UTC, IvanPizhenko commented
@larabr It have got strange CI failure, unrelated to code I've changed, please check https://github.com/openpgpjs/openpgpjs/runs/5148415229?check_suite_focus=true

2022-02-18 10:30 UTC, larabr requested changes

2022-02-18 10:30 UTC, larabr commented on openpgp.d.ts
> +  public verify(key: AnyKeyPacket, signatureType: enums.signature, data: string | object, date?: Date, detached?: boolean, config?: Config): Promise<void>; // throws on error
```suggestion
  public verify(key: AnyKeyPacket, signatureType: enums.signature, data: Uint8Array | object, date?: Date, detached?: boolean, config?: Config): Promise<void>; // throws on error
```

The error was about it being a `string`. In this case the documentation is incorrect, could you also update it?

2022-02-18 11:45 UTC, IvanPizhenko commented
@larabr Updated that doc comment

2022-02-18 19:20 UTC, merged

2022-03-02 19:46 UTC, IvanPizhenko commented
@larabr when do you plan to publish a new release with this thing included?

2022-03-02 20:44 UTC, twiss commented
@IvanPizhenko I've released [v5.2.0](https://github.com/openpgpjs/openpgpjs/releases/tag/v5.2.0) :)